version: '3'

vars:
  ENV: '{{.ENV | default "staging"}}'
dotenv:
  - .env
includes:
  global:
    taskfile: ./global/Taskfile.yaml
    dir: ./global
  infra:
    taskfile: ./infra/Taskfile.yaml
    dir: ./infra
tasks:
  default:
    cmds:
      - task: global:init
      - task: infra
