version: '3'

tasks:
  default:
    cmds:
      - task: init
      - task: apply
  init:
    dir: "./{{.ENV}}"
    cmds:
      - tofu init -upgrade
  plan:
    deps: [init]
    dir: "./{{.ENV}}"
    cmds:
      - tofu plan
  apply:
    deps: [init]
    dir: "./{{.ENV}}"
    cmds:
      - tofu apply -auto-approve
