- name: Remove enterprise repositories
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    update_cache: false
    state: absent
  loop:
    - deb https://enterprise.proxmox.com/debian/ceph-quincy trixie enterprise
    - deb https://enterprise.proxmox.com/debian/pve trixie pve-enterprise

- name: Enable Proxmox VE No-Subscription repository
  ansible.builtin.apt_repository:
    repo: deb http://download.proxmox.com/debian/pve trixie pve-no-subscription
    state: present
