- name: Add Tailscale signing key
  ansible.builtin.apt_key:
    url: "https://pkgs.tailscale.com/stable/debian/bookworm.noarmor.gpg"
    state: present

- name: Add Tailscale repository
  ansible.builtin.apt_repository:
    repo: "deb https://pkgs.tailscale.com/stable/debian bookworm main"
    state: present

- name: Install Tailscale
  ansible.builtin.apt:
    name: tailscale
    state: present
